using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using static System.Windows.Forms.LinkLabel;

namespace BELoader
{

    public partial class BeLoaderMain : Form
    {

        List<System.Windows.Forms.ToolTip> tooltips = new List<System.Windows.Forms.ToolTip> { };

        public BeLoaderMain()
        {
            InitializeComponent();
        }

        private void BeLoaderMain_Load(object sender, EventArgs e)
        {
            
            Helpers.SetMultilineToolTip(TextBoxHexFile, tooltips, new string[] { "Here is the hexfile generated by the code","It will be loaded internally, checked, and prepared"});
            Helpers.SetMultilineToolTip(BottonSelectHexFile, tooltips, new string[] { "Press to select the hexfile generated by the code", "It will be loaded internally, checked, and prepared" } ); 
        }

       /* 
        * Select a hex file for loading 
        */
        private void BottonSelectHexFile_Click(object sender, EventArgs e)
        {
            using (OpenFileDialog dlg = new OpenFileDialog())
            {
                dlg.Title = "Select HEX File";
                dlg.Filter = "HEX files (*.hex)|*.hex";
                dlg.DefaultExt = "hex";
                dlg.CheckFileExists = true;
                dlg.CheckPathExists = true;

                if (dlg.ShowDialog() == DialogResult.OK)
                {
                    string filename = dlg.FileName;

                    // Double-check extension
                    if (System.IO.Path.GetExtension(filename).Equals(".hex", StringComparison.OrdinalIgnoreCase))
                    {
                        // MessageBox.Show("Selected HEX file: " + filename);
                        // Test that the file is legitimate 
                    }
                    else
                    {
                        MessageBox.Show("You must select a file with the .hex extension.", "Invalid file",
                                        MessageBoxButtons.OK, MessageBoxIcon.Warning);
                    }
                }
            }

        }
    }
}
